#!/bin/bash

black_path=$(command -v black)
if [ ! -x "${black_path}" ]; then
  echo "ERROR: 'black' formatter is not found in path. Please ensure it's installed."
  exit 1
fi

pyflakes_path=$(command -v pyflakes)
if [ ! -x "${pyflakes_path}" ]; then
  echo "ERROR: 'pyflakes' tool is not found in path. Please ensure it's installed."
  exit 1
fi

changed_python_files=$(git diff --cached --name-only --diff-filter=ACM | egrep '^.+\.py$')
if ! [ -z "${changed_python_files}" ]; then
  pyflakes $changed_python_files || (echo "ERROR: 'pyflakes' found issues, aborting commit" && exit 1)
  black $changed_python_files
  git add $changed_python_files
fi
